### ISSUE TITLE
Info needed 

### ISSUE THREAD

**Issue by Cre8tiveDigital** [leemunroe/grunt-email-workflow#100]
Hi, I was just wondering did you or anyone ever get the grunt mailgun task to send out more than one email test if there are multiple folders containing emails?

Thanks

**Comment by taeo** [comment]
@Cre8tiveDigital - Here's an _example_ how you'd do it.

Create the file `/grunt/massmail.js` with the following code:
```
// Massmail
module.exports = function(grunt) {
    grunt.registerTask('massmail', 'Send bunches of email, quickly ✌🏽.', () => {
        const { dist } = grunt.config.get('paths');

        // Allow matching pattern via --pattern="", default to all (*)
        const pattern = grunt.option('pattern') || '*';

        // Get and loop .html files matching the given pattern in /dist
        const files = grunt.file.expand(`${dist}/${pattern}.html`);

        files.forEach((filepath) => {
            const filename = filepath.split('/').pop();
            grunt.option('template', filename);
            grunt.task.run('mailgun');
        });
    });
};
```

Then you can just run `grunt massmail --pattern="somefolder/*"`
The `--pattern` option allows you to get as clever as you want and will match all `.html` files with that pattern. **WARNING** the sample code will send all templates in the root `/dist` folder by default.

**Comment by taeo** [comment]
@Cre8tiveDigital - Did you ever give this a go or come up with an alternate solution?
