### ISSUE TITLE
support specific style file for different layout

### ISSUE THREAD

**Issue by irvin** [leemunroe/grunt-email-workflow#107]
It's easy to add new layout, but I don't find a way to assign different style for each layouts, that make it difficult to manage multiple functional email in one place.

**Comment by taeo** [comment]
Hey @irvin 

We've got your back - it's setup to support as many unique or shared styles as you'd like.

1. Create a new scss file`src/css/scss/layout_b.scss` for example. `@import` whatever shared styles or unique styles you'd like.
2. Edit [grunt/sass.js](https://github.com/leemunroe/grunt-email-workflow/blob/master/grunt/sass.js) and add reference to your new scss file.
```js
files: {
    '<%= paths.src %>/css/main.css': '<%= paths.src %>/css/scss/main.scss',
    '<%= paths.src %>/css/layout_b.css': '<%= paths.src %>/css/scss/layout_b.scss'
}
```
3. Create your new layout `src/layouts/layout_b.hbs` and change the stylesheet reference.
```html
<link href="../src/css/layout_b.css" media="all" rel="stylesheet" type="text/css" />
```

**Comment by irvin** [comment]
Thanks a lot!

I think this may go into document?
