### ISSUE TITLE
node version and setup

### ISSUE THREAD

**Issue by ntindicator** [leemunroe/grunt-email-workflow#136]
When the setup commands are run, and the correct node version is not installed the `nvm use` command didn't work. 

To fix it I ran `nvm install lts/erbium`. I found it a bit confusing to get started until I worked that this was missing.

Setup commands:
  ```
git clone https://github.com/leemunroe/grunt-email-workflow.git
  cd grunt-email-workflow
  nvm use
  npm install
```

**Comment by leemunroe** [comment]
Good point, this is not required. Removing this line from readme
