### ISSUE TITLE
[package] grunt-s3 unmaintained

### ISSUE THREAD

**Issue by taeo** [leemunroe/grunt-email-workflow#27]
The [s3 package](https://github.com/pifantastic/grunt-s3) is "Unmaintained!" according to the author (see screenshot). #21 
FYI @clecompte 

I've used this package before for s3 which works fine, is stable and people are actively working on it.
https://github.com/MathieuLoutre/grunt-aws-s3

![screen shot 2015-03-22 at 10 40 30 pm](https://cloud.githubusercontent.com/assets/1403363/6774854/872c7a68-d0e4-11e4-9fdc-e17ac8400a80.png)

**Comment by clecompte** [comment]
Thanks -- I'll check it out and see about updating it to a supported version.

**Comment by clecompte** [comment]
I have a better version of s3 coded and working. Will test further and send a PR shortly. Thanks @taeo for pointing this out!

**Comment by taeo** [comment]
@leemunroe - why closed? This issue is still on master.

**Comment by leemunroe** [comment]
@taeo Good point, reopening until pr merged
