### ISSUE TITLE
[Suggestion] LESS preprocessor alternative

### ISSUE THREAD

**Issue by brandonb927** [leemunroe/grunt-email-workflow#29]
It'd be really cool to use LESS CSS instead of SASS for building template CSS. Any interest in this, worth pursuing?

**Comment by taeo** [comment]
@brandonb927 - My 10¢ is that this is a starter kit that already supports a css pre-processor. If you prefer less to sass, you can download this project and make those preference-based changes.

**Comment by leemunroe** [comment]
@brandonb927 My thinking is similar to @taeo, I'm fearful of adding and maintaining too many things. Although a link to a forked version w/ LESS support wouldn't do any harm.
