### ISSUE TITLE
[Suggestion] Alternate templating engines

### ISSUE THREAD

**Issue by brandonb927** [leemunroe/grunt-email-workflow#30]
I love handlebars, but it'd be really nice to be able to choose Nunjucks, or other templating engines with this plugin. Could be separate tasks, etc.

**Comment by leemunroe** [comment]
@brandonb927 I'd rather not support multiple templating engines here. Reasons being I could see it growing out of control and I see this more of a grunt starter kit that you can modify with your own prefs.

Happy to link to a forked version from the readme if you have one ready though?

**Comment by brandonb927** [comment]
No worries, I was going to take this on myself and just thought I'd ask if this was something in the works first.

**Comment by martinbutler** [comment]
Hi @brandonb927 ,
is there a way to 'escape' the handlebars? i would like the generate a html with something like:
Dear {{ first_name }},

thanks in advance.

**Comment by taeo** [comment]
@martinbutler it's possible to escape the line using a backslash
```
\{{ first_name }}
```

__OR__

You can use an alternate syntax such as:
`[[ first_name ]]` > `{{ first_name }}`

Then and then add a custom regex via grunt task to replace it:
```
patterns: [ {
    match: /(\[\[)([^\]\r\n]+)(\]\])/gi,
    replacement: '{{ $2 }}'
}]
```

Better to post a new issue / question in an issue that isn't closed :)

**Comment by martinbutler** [comment]
@taeo thank you taeo. i pulled down the question b/c i did find the solution looking at the assemble.io repo, but i guess you were responding at the same time!

thank you for the additional suggestion on the regex.

cheers!
