### ISSUE TITLE
[Suggestion] Use grunt load tasks

### ISSUE THREAD

**Issue by taeo** [leemunroe/grunt-email-workflow#31]
Using [Grunt Load Tasks](https://github.com/sindresorhus/load-grunt-tasks) would help condense the gruntfile and eliminate the need to do this > `grunt.loadNpmTasks('CONTRIBNAME');` over and over.

**Comment by leemunroe** [comment]
@taeo Nice. This would tidy it up nicely. Happy to accept PR for this.
