### ISSUE TITLE
Task flow mind map and paths.

### ISSUE THREAD

**Issue by taeo** [leemunroe/grunt-email-workflow#32]
@leemunroe & @clecompte 
I'm trying to get my head around some of the image path related flow we're seeing that will result in inconsistent behavior for  #26 #25 and #28

Here's my stab at a high level outline. Your thoughts?
(Let me know if you think i'm crazy...)

- assemble
    - premailer
        - imagemin
            - __TASK NEEDED__ to replace  `./dist/*.html` files image sources from `./src/img` to `./dist/img`

Anything sent to cdn (cloudfiles, aws, etc..) and replaced in cdn task(s) should always have `/dist/img/` consistent or this falls apart.

- cloudfiles || aws_s3
  (should send `./dist/img/**/*.{png,jpg,gif}` to: `http://cdnurl.com/some-optional-path/`+`dist/img/**/*.{png,jpg,gif}`)

    - cdn: cloudfiles || aws_s3
    (should replace `./`dist/img/PATH-TO-FILE with `http://cdnurl.com/some-optional-path/`)

**Comment by leemunroe** [comment]
@taeo I think you nailed it.

**Comment by taeo** [comment]
@leemunroe - Word. Preference on how we want to go about this and who's doing what?

FYI - @clecompte
