### ISSUE TITLE
[question] Setting the email clients for litmus

### ISSUE THREAD

**Issue by aminmeyghani** [leemunroe/grunt-email-workflow#37]
Is it possible to set the email clients for testing with Litmus? Like passing the configuration an array of clients: `[ "all outlook", "thunderbird" ]` and so on ?

If not, how does the task decide which clients to choose? I can't figure it out.

Thanks!

**Comment by leemunroe** [comment]
@aminmeyghani Yes you can alter the list of clients in [Gruntfile.js](https://github.com/leemunroe/grunt-email-workflow/blob/master/Gruntfile.js#L243). 

Find the client values through this Litmus URL https://{your_company}.litmus.com/emails/clients.xml
