### ISSUE TITLE
Dependency deprecation

### ISSUE THREAD

**Issue by newswim** [leemunroe/grunt-email-workflow#39]
Running `npm install` on npm v2.5.1 threw a bunch of deprecation warnings. Example:

```
ERROR: Premailer gem not installed. Issue "gem install premailer" to install it
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```

```
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
```

```
npm WARN engine pkgcloud@0.9.6: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
```

Just wondering if this is on your radar.

**Comment by leemunroe** [comment]
Just upgraded to 2.11.2 and didn't notice any issues.

Premailer gem, unfortunately, is Rails dependent so if you happen to be on a different Rails version then you'd have to reinstall it.

**Comment by leemunroe** [comment]
@newswim I see what you mean about the npm warnings now. What's the best practice to dealing with such things?

**Comment by newswim** [comment]
Not sure, I got everything working after installing premailer independently. Perhaps check on current package versions and set them with '>=`. Check out these articles:

https://nodesource.com/blog/semver-tilde-and-caret
http://blog.nodejitsu.com/package-dependencies-done-right/ (older article)
https://github.com/npm/node-semver --- library for semvar parser

**Comment by newswim** [comment]
@leemunroe Did you see the release notes for NPM 3.0? It's only about 3 days old atp -- https://github.com/npm/npm/releases/tag/v3.0.0

Check out the section about the new `npm install` functionality.

**Comment by leemunroe** [comment]
@newswim Interesting. Thanks for pointing it out. Looks like package.json will need some additional info.

**Comment by leemunroe** [comment]
Closing as I don't think there's anything we can do about this now.

**Comment by newswim** [comment]
I know they're working hard at NPM.. we should see a best currently
possible solution soon.
