### ISSUE TITLE
premailer error

### ISSUE THREAD

**Issue by xavierartot** [leemunroe/grunt-email-workflow#42]
Hi,
I start grunt in the console and I have an error with premailer:

[grunt-email-workflow master] grunt
Running "sass:dist" (sass) task

Running "assemble:pages" (assemble) task
Assembling dist/branded.html OK
Assembling dist/transaction.html OK
>> 2 pages assembled.

Running "premailer:html" (premailer) task
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- premailer (LoadError)
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/xavi/sites/email/grunt-email-workflow/node_modules/grunt-premailer/lib/premailer.rb:3:in `<main>'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- premailer (LoadError)
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/xavi/sites/email/grunt-email-workflow/node_modules/grunt-premailer/lib/premailer.rb:3:in `<main>'
Fatal error: /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- premailer (LoadError)
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/xavi/sites/email/grunt-email-workflow/node_modules/grunt-premailer/lib/premailer.rb:3:in `<main>'
[grunt-email-workflow master] 

Thank you

**Comment by xavierartot** [comment]
EDIT:
I installed gem install premailer and it works.

**Comment by bojingo** [comment]
In case anyone comes across this, hpricot is apparently not supported and I could not install the gem (see http://stackoverflow.com/questions/11605404/installing-hpricot). I did gem install nokogiri instead and it worked great.
