### ISSUE TITLE
Feature request: Implement browser sync

### ISSUE THREAD

**Issue by xavierartot** [leemunroe/grunt-email-workflow#44]
Each time I have a change the server connect well and disconnect?

I add it int registerTask:
   `grunt.registerTask('default', ['browserSync','sass','assemble','premailer','imagemin','replace:src_images']);`

 Then after the litmus part.
`browserSync: {
  dev: {
    bsFiles: {
      src : [
        '<%= paths.dist %>/*.html'
      ]
    },
    options: {
      watchTask: true,
      server: "http://localhost:8888/grunt-email-workflow/dist/transaction.html"
    }   
  } 
}`

Thanks

**Comment by xavierartot** [comment]
Livereload works well

**Comment by taeo** [comment]
@xavierartot - Checkout #33 and let us know if that's a preferable alternative to browsersync. It supports watch, live reload, browser preview(s) and quick nav to jump between compiled templates.

If you aren't feeling it, I can provide some sample code for BrowserSync to work with this project.

**Comment by taeo** [comment]
More directly, I'd consider adding a task. What's important is that `watch` is called after `browserSync`.
`grunt.registerTask('giddyup', ['default','browserSync', 'watch']);`

**Comment by xavierartot** [comment]
That ok, I saw your repo, and is look really nice, I'd like the auto-prefixer.
Do I have some exemple with BrowserSync?
Thank you.

**Comment by leemunroe** [comment]
@xavierartot Did #33 and livereload solve this for you?

I don't have much experience with BrowserSync. Is there something it offers that we don't already have?
