### ISSUE TITLE
cdnify weirdness

### ISSUE THREAD

**Issue by toby1kenobi** [leemunroe/grunt-email-workflow#45]
It's probably just me, but I can't get the cdnify/cloudfiles part to work properly with Rackspace. What I'm seeing is image assets are uploaded to my container, in 

    <rackspace container>/src/img/...

but the paths in my emails get changed to 

    http://<rackspace uri>/dist/img/...

**Comment by taeo** [comment]
@toby1kenobi - It's not you. The cloudfiles task was never updated properly when imagemin was implemented. We'll get a fix / PR for this.

[Line 173 of Gruntfile.js](https://github.com/leemunroe/grunt-email-workflow/blob/master/Gruntfile.js#L173) should be `'src': '<%= paths.dist_img %>/*',` NOT `'src': '<%= paths.src_img %>/*',`

**Comment by toby1kenobi** [comment]
Thanks!

**Comment by leemunroe** [comment]
Pushed a fix.

@taeo Thanks for the solution
