### ISSUE TITLE
[Suggestion] - Convert Gruntfile from .js to .coffee

### ISSUE THREAD

**Issue by taeo** [leemunroe/grunt-email-workflow#46]
First off. I'm not huge coffee script fan, but it does make Gruntfiles a lot more readable IMO.
Can create a PR for this https://github.com/taeo/grunt-email-design/commit/5440f143b1e94a425c71edb0e43cfdeda21ea2d7 if people are feeling it.

**Comment by leemunroe** [comment]
Commenting on the [wrong repo](https://github.com/taeo/grunt-email-design/commit/5440f143b1e94a425c71edb0e43cfdeda21ea2d7) :)

**Comment by taeo** [comment]
Passe with your restructure https://github.com/leemunroe/grunt-email-workflow/commit/eb2a79c8cc99c8756efac391b505b54754d3ec70
