### ISSUE TITLE
Inlined images (breaks in gmail)

### ISSUE THREAD

**Issue by olapersson** [leemunroe/grunt-email-workflow#49]
Is there any reason not to set webResources.images to false? Gmail doesn't display inlined images, I think it's worth the extra requests to have them linked rather than inlining small images and having them break in gmail.

Seems like it'd be sensible to remove the inlining from the defaults. I can open a PR.

    juice: {
      your_target: {
        options: {
          [...]
          webResources: {
            images: false
          }
        },
    },

**Comment by leemunroe** [comment]
@olapersson Agreed. Are images being inlined for you currently? Having trouble reproducing, what steps should I take?

**Comment by olapersson** [comment]
Here's an example (small png added in the branded template) where the image gets embedded:
https://github.com/olapersson/grunt-email-workflow/tree/inline-image-repro

For reference, the same thing after the configuration change:
https://github.com/olapersson/grunt-email-workflow/tree/inline-image-repro-fixed

Opened a pull request with the change #50.
