### ISSUE TITLE
Can't run default task without error on imagemin task

### ISSUE THREAD

**Issue by mitchrenton** [leemunroe/grunt-email-workflow#61]
Hey, 
I've set this up as you've descibed in the repo, but I get an error on the imagemin task...

>Fatal error: Cannot read property 'contents' of undefined

Any ideas what might be causing this?

**Comment by leemunroe** [comment]
Thanks. Got the same issue. Upgraded the imagemin version to `1.0.0` after finding [this](https://github.com/gruntjs/grunt-contrib-imagemin/issues/208).
