### ISSUE TITLE
Destination Sub-directories

### ISSUE THREAD

**Issue by 19peaches** [leemunroe/grunt-email-workflow#62]
Hi Lee,

I love this repo.  Up till now I've used it just for real small projects, but now I have a big project and I need to add sub-directories to my destination path to keep all these emails organized.

Globbing the src directory fetches them all correctly:

```js
src: ['<%= paths.src %>/emails/**/*.hbs'],
```

but can you please advise on how to retain my sub-directories in the `dist` directory?

Thanks.

**Comment by taeo** [comment]
You'd have to remove the `flatten: true` option as well from `/grunt/assemble.js`

The downside(s) to this currently are:
* The preview UI naively looks for `/dist/*.html` files, so template select will be blank. 
* You get more of the tree than you might want `/dist/src/emails/<templates + subdirs>`

**Comment by 19peaches** [comment]
Yeah this works but as you said, breaks a few other things like `juice` and image urls.

I wonder would it be better to create separate `grunt` tasks for each directory? Or perhaps even better, multiple tasks to `assemble`?

I tried this:
```js
module.exports = {
    front: {
        options: {
          layoutdir: '<%= paths.src %>/layouts',
          partials: ['<%= paths.src %>/partials/**/*.hbs'],
          helpers: ['<%= paths.src %>/helpers/**/*.js'],
          data: ['<%= paths.src %>/data/*.{json,yml}'],
          flatten: true
        },
        pages: {
          src: ['<%= paths.src %>/emails/front/*.hbs'],
          dest: '<%= paths.dist %>/front'
        }
    },
    back: {
        options: {
          layoutdir: '<%= paths.src %>/layouts',
          partials: ['<%= paths.src %>/partials/**/*.hbs'],
          helpers: ['<%= paths.src %>/helpers/**/*.js'],
          data: ['<%= paths.src %>/data/*.{json,yml}'],
          flatten: true
        },
        pages: {
          src: ['<%= paths.src %>/emails/back/*.hbs'],
          dest: '<%= paths.dist %>/back'
        }
    }
}
```
it doesn't throw an error, but it doesn't compile any files either.

**Comment by taeo** [comment]
I'd stay away from near-duplicate grunt tasks.

Ideal approach for what you're wanting to do would be to go through every grunt task and make sure it supported directory depth + add recursion to the preview app's template finder.

Another option would be to just prefix all your emails as opposed to having hierarchy. `/emails/back_<template_name>.hbs`

I personally don't foresee the need to support directory structure in `dist`, but maybe that's just me and/or I don't see the full picture.

Cheers

**Comment by 19peaches** [comment]
Right. Normally I wouldn't do something like this, but there are simply way too many emails in this projects to have them all dumped in a single folder. Approx 50 different templates or so right now.

I have however resolved the problem, after consulting the `grunt-assemble` repo I see that this is very simple:

```js
module.exports = {
    options: {
      layoutdir: '<%= paths.src %>/layouts',
      partials: ['<%= paths.src %>/partials/**/*.hbs'],
      helpers: ['<%= paths.src %>/helpers/**/*.js'],
      data: ['<%= paths.src %>/data/*.{json,yml}'],
      flatten: true
    },
    front: {
      src: ['<%= paths.src %>/emails/front/*.hbs'],
      dest: '<%= paths.dist %>/front/'
    },
    back: {
      src: ['<%= paths.src %>/emails/back/*.hbs'],
      dest: '<%= paths.dist %>/back/'
    }
};
```
Thanks for your help :)

**Comment by taeo** [comment]
Nice. Thanks for posting your solution :+1:

**Comment by leemunroe** [comment]
:+1:
