### ISSUE TITLE
Idea: Consider using Roadie

### ISSUE THREAD

**Issue by leemunroe** [leemunroe/grunt-email-workflow#63]
How does it compare to Juice?

https://github.com/mange/roadie

**Comment by taeo** [comment]
Not answering your question here, but avoiding ruby dependencies is pry a good move to keep this project more accessible. Roadie is ruby-centric.

**Comment by leemunroe** [comment]
Good point. Don't want to go back in that direction.

**Comment by leemunroe** [comment]
While Roadie looks interesting, it re-introduces ruby dep.
