### ISSUE TITLE
Other host for image

### ISSUE THREAD

**Issue by fionnayao** [leemunroe/grunt-email-workflow#65]
Hi Lee :smile: 

Is there a easy way to point all image source to a specified URL if we are hosting our own image? I thought about using updating grunt replace.js, but wasn't sure if that's the best way to go about it?

Any thoughts would be appreciated :)

**Comment by leemunroe** [comment]
Sure thing. Few ways you could do it. How do you upload your images to your host?

One way would be to use the [replace task](https://github.com/leemunroe/grunt-email-workflow/blob/master/grunt/replace.js) and replace the source path with your URL.
