### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by mtsweir** [leemunroe/grunt-email-workflow#68]
Running on Windows
I've run through the setup instructions, have added MailGun details too.

'grunt' works fine, but 'grunt serve' results in an error:
Assembling dist/branded.html Assembling dist/branded.html ERROR
Warning: Unable to create directory "path-to-project\email\grunt-email-workflow\grunt-ema
il-workflow\dist" (Error code: EPERM). Use --force to continue.

grunt was asking whether I had 'grunt-parallel' installed so I installed that also but still had the same issue.

Uninstalled 'grunt-parallel' as it made no difference, but now 'grunt' on it's own doesn't work now. Not really sure if it's a permission issue here but can't seem to get it to run.

/ UPDATE:
My bad, had a dist file open in my editor! Now all works fine. Sorry for any inconvenience. Really like this solution and will be implementing this for all my projects.

**Comment by leemunroe** [comment]
Solid. Glad you got it fixed. And would love to see any of the emails you produce!
