### ISSUE TITLE
Button partial error

### ISSUE THREAD

**Issue by mtsweir** [leemunroe/grunt-email-workflow#69]
Having an issue with the partial buttons, I get this error when running 'grunt'

Assembling dist/email.html ERROR
Warning: Parse error on line 32:
...     {{> button type="primary" align="ce
-----------------------^
Expecting 'CLOSE', 'CLOSE_UNESCAPED', 'STRING', 'INTEGER', 'BOOLEAN', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'DATA', 'SEP',
got 'EQUALS' Use --force to continue.

I'm also recreating this workflow from scratch so I can better understand how you've done it and why, so far my .json file has these dependencies:

"devDependencies": {
    "assemble": "^0.4.42",
    "grunt": "~0.4.5",
    "grunt-assemble": "^0.4.0",
    "grunt-cdn": "^0.6.5",
    "grunt-contrib-clean": "^0.7.0",
    "grunt-inline-css": "^0.1.5",
    "grunt-juice-email": "^0.1.4",
    "grunt-sass": "^1.1.0"
  }

// UPDATE

Might have resolved this by changing the loadNpmTask to 'grunt-assemble' from 'assemble'

**Comment by leemunroe** [comment]
Interesting. Now I'm wondering why and if I need both `assemble` and `grunt-assemble`. Let me know if you have any recommendations for tidying up dependencies.

**Comment by mtsweir** [comment]
thanks I got it working with grunt-assemble, there might be some variable changes.

Mine looks like:

// Assembles your email content with HTML layout
      assemble: {
        options: {
          layoutdir: 'src/layouts',
          partials: ['src/partials/**/*.hbs'],
          flatten: true
        },
        pages: {
          src: ['src/emails/*.hbs'],
          dest: 'dist/'
        }
      },
