### ISSUE TITLE
Build individual templates

### ISSUE THREAD

**Issue by mtsweir** [leemunroe/grunt-email-workflow#71]
If I wanted to run a grunt command to build individual templates is that possible?

e.g grunt templateOne or grunt templateTwo

**Comment by leemunroe** [comment]
Not currently. But you could use a flag to set something like that up e.g. `grunt build --template=templateOne` and then modify `aliases.yaml` and `assemble.js` to support it.

**Comment by mtsweir** [comment]
I'd love to see how you did the aliases part, and the way you configured your Gruntfile.js.
The way its constructed is really nice, is there any places I can learn how you set this up?

**Comment by leemunroe** [comment]
Sure, take a look at https://github.com/firstandthird/load-grunt-config
