### ISSUE TITLE
Issue with Grunt Express and Parallel dependency

### ISSUE THREAD

**Issue by leemunroe** [leemunroe/grunt-email-workflow#72]
Just recently `>> Local Npm module "grunt-parallel" not found. Is it installed?` has appeared when running grunt commands.

![image](https://cloud.githubusercontent.com/assets/15963/12901872/1b65d814-cebe-11e5-9daf-183b99d8d18a.png)

**Comment by jrutter** [comment]
I believe you can just run this "npm install grunt-parallel --save"  to add it

**Comment by cmacdonnacha** [comment]
`npm install grunt-parallel --save-dev` worked for me
