### ISSUE TITLE
cdn paths

### ISSUE THREAD

**Issue by mtsweir** [leemunroe/grunt-email-workflow#74]
the image path is:
../src/img/

then replacing this with a cdn url:
http://www.site-name.com/newsletters/img

results in:
http://www.site-name.com/newsletters/img/src/img

is there a way to replace with just the cdn url instead of them combining?

**Comment by leemunroe** [comment]
@mtsweir Good Q, not sure off hand. Curious if you were able to find a solution for this as it bugged me at first also.

**Comment by eldyvoon** [comment]
It's annoying the dist directory which in ur case is img/src, I solved that by altering the value of replace.js
```
...
patterns: [
        {
          match: /(<img[^>]+[\"'])(\.\.\/src\/img\/)/gi,  // Matches <img * src="../src/img or <img * src='../src/img'
          replacement: '$1../'
        },
        {
          match: /(url\(*[^)])(\.\.\/src\/img\/)/gi,  // Matches url('../src/img') or url(../src/img) and even url("../src/img")
          replacement: '$1../'
        }
      ]
...
```

**Comment by taeo** [comment]
This does solve the issue of the actual replaced path(s). That said here are the related issues it creates that makes it incomplete for the workflow to function.

1. Breaks images in preview (images are still written to `dist/img/` but source files ref `../`
2. CDN Upload tasks for S3 & Cloudfiles do not write to the root / base folder

**Comment by eldyvoon** [comment]
@taeo Agreed. I actually have to adjust few path to make it to work.

**Comment by taeo** [comment]
As is, this works.

1. In your templates, just use `src="img/FILENAME` _(../src/)_ isn't needed.

Upload the `/dist` folder to your server. Done.

**If you need a cdn for images,  here's an example with cloudfiles**

```
{
    "cloudfiles": {
        "uri": "http://mydomain.com/myfolder/"
    }
}
```

```
mattbain@sole ~/S/_/grunt-email-workflow> grunt cdn:cloudfiles
Running "cdn:cloudfiles" (cdn) task

cdn:html - branded.html
cdn:html - components.html
cdn:html - transaction.html

Changing /img/mailgun.png -> http://mydomain.com/myfolder/img/mailgun.png
```
