### ISSUE TITLE
Windows 8 with native CMD

### ISSUE THREAD

**Issue by danilomatos** [leemunroe/grunt-email-workflow#78]
Hey, I'm trying to run npm install on windows 8 width native CMD and I get many many WARNs, and then, this happens and it is just stuck, no further info.

http://postimg.org/image/eqg7imu53/

**Comment by leemunroe** [comment]
@danilomatos I think these are warnings for dependencies that are out of date. The workflow should still work though. What happens when you run `grunt`?

**Comment by leemunroe** [comment]
I'm afraid I don't have a Windows environment to test this on. Can some one try this with latest dependencies and see if that has fixed things?

**Comment by taeo** [comment]
Closing this one out @danilomatos - feel free to open a new ticket if you're still using this project and having issues.
