### ISSUE TITLE
Mailgun 403

### ISSUE THREAD

**Issue by adyz** [leemunroe/grunt-email-workflow#81]
I haven't started used this project in a while, but recently I opened the project to create an email template and everything worked awesome as usual (great time saver!!!) but the mailgun task returns a 403 error
![screen shot 2016-12-22 at 10 09 28](https://cloud.githubusercontent.com/assets/611174/21419234/2a56beae-c82f-11e6-8e1b-6162861bb39d.png)
. 

Not sure where this error comes from, is this happening to you too?

**Comment by adyz** [comment]
I think they are not letting us send the email without a domain. I see this in their log: 


```Rejected: 'This is a test email' Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings.: ```

**Comment by leemunroe** [comment]
@adyz Looks like Mailgun updated some things recently for security purposes. The workflow should still work but you'll have to add your own domain and verify it on Mailgun.

http://blog.mailgun.com/domain-verification-changes-for-new-and-existing-domains/

**Comment by leemunroe** [comment]
@adyz Or you can still use the sandbox but just have to add the recipient as a authorized address https://help.mailgun.com/hc/en-us/articles/217531258

**Comment by adyz** [comment]
@leemunroe Thank you very much!
