### ISSUE TITLE
Mailgun no longer working

### ISSUE THREAD

**Issue by williamdavies90** [leemunroe/grunt-email-workflow#83]
Firstly thank you so much for this amazing workflow, it has made my life so much easier.

The last month or so I have noticed the mailgun task is no longer working. I have done some digging around and it would seem mailgun have updated their API but unfortunately I have not been successful in updating and changing this within the workflow. If its any help windows 10 throws a 301 error and OSX appears to send the email but it doesnt work.

Many thanks.

**Comment by VanGTO** [comment]
I can confirm same issue as @williamdavies90 - I ran a test run about half an hour ago and it's not appearing in the Mailgun logs. Lasrt run i sent successfully, was on 22 Feb 2017. So it appears something has changed between then and now.

**Comment by rwillwerth** [comment]
Yes. Having the same issues... same time frame.

**Comment by markhuge** [comment]
@leemunroe I'm updating the upstream packages your repo depends on with the new API implementation.   I'll send a PR with the updated package version of grunt-mailgun once I'm done.
