### ISSUE TITLE
Get this error for mailgun

### ISSUE THREAD

**Issue by rwillwerth** [leemunroe/grunt-email-workflow#85]
```
Loading "mailgun.js" tasks...ERROR

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Warning: Task "mailgun" not found. Use --force to continue.
Aborted due to warnings.
```

I sent @markhuge a pull request to his `node-mailgun-send` that fixes this issue.

**Comment by taeo** [comment]
Looks like your [PR is still lingering](https://github.com/markhuge/node-mailgun-send/pull/4).

I was able to send mailgun emails just fine with the `grunt send --template=[THE_TEMPLATE_NAME]` command.

@rwillwerth - What is your node version? That could be an issue if you're on an older version. I'm on v7.x
`node --version`

**Comment by markhuge** [comment]
This is going to sound really pedantic, but I've had to stop accepting PRs  (however trivial) for issues that are not effecting current LTS. 

This doesn't seem to be an issue in 6.x which is the current LTS.

**Comment by taeo** [comment]
Nothing wrong with that, Mark. Thanks.

We can call this closed.
