### ISSUE TITLE
Support Gulp?

### ISSUE THREAD

**Issue by leemunroe** [leemunroe/grunt-email-workflow#86]
I get asked a lot about supporting this workflow in gulp, which I'm definitely open to given the [adoption it has](http://stateofjs.com/2016/buildtools/).

I'm wondering if it makes sense to have a project that supports both grunt and gulp. The idea being that we're using the same `/src` files but the developer can decide to use grunt or gulp to run the build tasks depending on their preference.

Open to responses on whether this is a good or bad idea, if it even makes sense, and what the downsides are?

**Comment by VanGTO** [comment]
Sounds good. It's always good to have options/redundancies. 

To that end, I have been meaning to ask if you had appetite to add options for other transactional mail vendors. I'm specifically looking at AWS SES. I'm looking to try and replicate your grunt (and/or gulp process once developed) for SES. Thus allowing another option and having a redundancy in place should things go a bit 'Pete Tong'.

Thoughts?

**Comment by leemunroe** [comment]
@VanGTO Absolutely lets do it. I think the way it is modularized now, where each grunt task has it's own file, makes this great for plugging in new options.

**Comment by taeo** [comment]
On the grunt -vs- gulp -vs- both scene, I'd recommend **not** trying to support both. Seems like a recipe for headaches and redundant code that needs to be kept in sync and maintained.

I'd be curious to hear any specifics about why gulp would be *better*, or if just a cooler/newer thing. Installing and running `npm install && run task` is equally simple in both worlds.

If there's a huge cry for gulp over grunt, we could just port everything.

**Comment by taeo** [comment]
@leemunroe & @VanGTO - close this issue or keep it open? _(I vote close)_
If y'all want to go gulp, I suggest creating a new repo 'gulp-email-workflow' and abandoning this one.

**Comment by leemunroe** [comment]
Yep lets close for this repo. A task runner agnostic workflow would be pretty cool though — something that doesn't require users to know/learn Grunt or Gulp. Separate topic :-)
