### ISSUE TITLE
Only run necessary tasks when in grunt serve

### ISSUE THREAD

**Issue by andersan** [leemunroe/grunt-email-workflow#88]
Hello, 

Is there any way to only run relevant tasks when new files are added and the local server is running? I would like to be able to change a css file without imagemin running again, for example. Or is it better to just remove files from the src folder so they no longer affect the process?

**Comment by romanlelek** [comment]
Hello, 

I think that you can define, which of your tasks should run in grunt/watch.js by parameter tasks:
`preview_dist: {
    files: ['./dist/*'],
    tasks: [],
    options: {
      livereload: true
    }
  },`
When empty - it runs grunt's 'default' task. But you can add you own sequence of tasks e.g. forexample without imagemin.

Best regards,
Roman

**Comment by taeo** [comment]
Chris, @romanlelek is mostly correct. 

You would have to edit `/grunt/aliases.yml` to add a custom series of tasks. You would also need to modify or copy/rename some of the `/grunt/*js` tasks to suit your needs.

Issue #57 is along these lines as a feature request.

**Comment by andersan** [comment]
Thanks for the responses! I edited aliases.yml and made a separate task for minimizing images, removing it from the default tasks.

// Where we tell Grunt what to do when we type "grunt" into the terminal
// $ grunt
default:
  - 'clean'
  - 'sass:dist'
  - 'assemble'
  - 'juice'

// Compress images
// $ grunt min
min:
  - 'imagemin'
  - 'replace:src_images'
