### ISSUE TITLE
UI for this project

### ISSUE THREAD

**Issue by cjcorney** [leemunroe/grunt-email-workflow#92]
Hi All,

Not an issue but more a question or an opportunity for a developer. Wondering if anyone created a UI for this workflow they could share or would be interested in developing?

Cheers,

Chris

**Comment by leemunroe** [comment]
This would be amazing. @cjcorney Do you have any ideas or sketches to share to get the conversation going?

**Comment by cjcorney** [comment]
Hi Lee,

My developer and I have been working on a prototype but due to the systems
we use (Strongview is our ESP and frankly belongs in a museum) and the way
the templates are currently setup to serve four languages has made life a
bit tricky. I'll share some screenshots next week though as to what we've
been able to do so far in terms of generating multiple files etc :)

**Comment by cjcorney** [comment]
Hi Lee,

Our progress to date below:

http://tinypic.com/r/r2rxup/9

For now we're going back to the CLI and adapting our new templates into the various components etc. Our main issue is that our Strongview templates are setup to use variables for each language which is proving a pain.

Also wondering if there is a way to send all templates form the dist folder in your example rather than just a specific one? Using your git example each time I run grunt send --template=*.html I am sent the last .html file in the folder (transaction.html) three times rather than each email once.

**Comment by leemunroe** [comment]
1. This is looking really impressive.

2. I'm afraid not. I get the same thing using `*.html`. Possibly a bug with https://github.com/markhuge/grunt-mailgun

**Comment by leemunroe** [comment]
@cjcorney Wondering if you made any progress with this project?

**Comment by taeo** [comment]
@cjcorney - Any update here or should we close this issue?

**Comment by leemunroe** [comment]
Closing. But I would love to see any progress from @cjcorney
