### ISSUE TITLE
Using FTP not CDN?

### ISSUE THREAD

**Issue by jzantua** [leemunroe/grunt-email-workflow#93]
Hi @leemunroe i wanted to try and test your wonderful project but using ftp for images

 can you help me sort this out ?  any ideas ? or workaround ?

 willing to support in a small way after i finish this up ^_^v

**Comment by leemunroe** [comment]
Have you looked at something like https://www.npmjs.com/package/grunt-ftp?

I haven't used it, but looks like you could use this in place of the S3/Cloudfiles task to upload your images directory. Then you would create a CDN option for replacing local paths with your FTP absolute path.

**Comment by jzantua** [comment]
Hi @leemunroe  thanks for the great reference 👍 !

ill try to catch up using this one :)

but is it ok if had some trouble using this 'grunt-ftp' can you assist me using it ? 🥇

**Comment by leemunroe** [comment]
Of course. Feel free to share in this thread so others can see and help also.

**Comment by jzantua** [comment]
done doing it via FTP but getting an error when connecting to ftps /sftp any thoughts ? already put the right credentials but still getting an error  does connecting ftp and ftps /sftp is different ? maybe because ftps /sftp need some ssl certificate before passing through ? ANY THOUGHTS ?

**Comment by taeo** [comment]
Hey @jzantua - Can you post a sample of the configuration you're using and confirm it you are using this package (https://www.npmjs.com/package/grunt-ftp) or something else?

**Comment by jzantua** [comment]
Hi @taeo im using this package (https://www.npmjs.com/package/ftp-deploy)

**Comment by taeo** [comment]
@jzantua - Yep, authentication is definitely required and unsupported. At the very top of the readme for the [ftp-deploy](https://github.com/simonh1000/ftp-deploy) package is says "(Need sftp? Check out [sftp-upload](https://github.com/pirumpi/sftp-upload))".

**Comment by jzantua** [comment]
thanks @taeo  will try this and share to you guys when im 💯 percent done 👍 thanks for all of the assistance

**Comment by leemunroe** [comment]
@jzantua Did you get this working?

**Comment by jzantua** [comment]
hi @leemunroe yes i tried but only for works ftp not for sftp current stop doing it for a while it gives me headache ill share the files when i got back to my station :)

**Comment by taeo** [comment]
@jzantua - Did you have finished sample code or a PR for this?
