### ISSUE TITLE
s3upload uploads to wrong folder

### ISSUE THREAD

**Issue by Lieneke** [leemunroe/grunt-email-workflow#98]
when using s3upload, the images are uploaded to bucket/dist/img/image.png but the html is changed to bucket/img/image.png.

**Comment by taeo** [comment]
@Lieneke - What does your `secrets.json` look like for s3 "bucketdir" and "bucketuri"?
_(Be sure not to post any secret keys)_ :)

```
  "s3": {
    "bucketdir": "AMAZON S3 BUCKET SUBDIRECTORY (optional)",
    "bucketuri": "AMAZON S3 PATH (ex: https://s3.amazonaws.com/)"
  }
```

**Comment by taeo** [comment]
Noting this relates to #74

**Comment by taeo** [comment]
With the default command `cdn:aws_s3` and these settings:

```
{
    "s3": {
        "bucketdir": "bucketdir",
        "bucketuri": "https://s3.amazonaws.com/",
        "bucketname": "bucketname"
    }
}
```

I get the expected html mutation for the paths uploaded to s3.
```
mattbain@sole ~/S/_/grunt-email-workflow> grunt cdn:aws_s3
Running "cdn:aws_s3" (cdn) task

cdn:html - branded.html
cdn:html - components.html
cdn:html - transaction.html

Changing /dist/img/mailgun.png -> https://s3.amazonaws.com/bucketname/bucketdir/dist/img/mailgun.png

Done.
```

Can you provide any further details to diagnose?

**Comment by taeo** [comment]
@Lieneke - Did this solve your issue?
